### ISSUE TITLE
能否支持静音播放

### ISSUE THREAD

**Issue by ncnk** [pili-engineering/QPlayer2-IOS#2]
场景是同时启动两个播放器，其中主屏正常播放，副屏静音播放。
然后允许用户在两个播放器之间切换，同时每个播放器的声音也可以独立控制打开、关闭

**Comment by AstaTus** [comment]
目前暂时不支持，后续会加上静音播放能力。

**Comment by Mengwangchao** [comment]
静音播放在1.2.0版本已支持
