### ISSUE TITLE
最新版本 pod 安装失败

### ISSUE THREAD

**Issue by zanyfly** [pili-engineering/QPlayer2-IOS#32]
错误提示如下，最新版本不能访问
Installing qplayer2-core 1.4.3 (was 1.2.2)

[!] Error installing qplayer2-core
[!] /usr/bin/curl -f -L -o /var/folders/_k/bqjysv5s5sv0cjpndnsg18n80000gn/T/d20240625-77077-zhv19g/file.zip https://sdk-release.qnsdk.com/qplayer2-core-v1.4.3.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.15.2 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to sdk-release.qnsdk.com port 443 after 10 ms: Couldn't connect to server

**Comment by duguqiubai6188** [comment]
我遇到同样的问题，是怎么解决的

**Comment by zanyfly** [comment]
提交工单，获取授权
