### ISSUE TITLE
PLPlayer播放m3u8视频没有声音

### ISSUE THREAD

**Issue by ismilesky** [pili-engineering/QPlayer2-IOS#8]
PLPlayer 播放m3u8视频没有声音，地址: http://219.151.31.38/liveplay-kk.rtxapp.com/live/program/live/hnwshd/4000000/mnf.m3u8， 使用VLC是有声音的

**Comment by AstaTus** [comment]
PLPlayer 已经不维护 请尽快迁移至QPlayer2
